/**
 * It returns the greatest id in the given array.
 * It can be useful when updating arrays that used in components.
 * Unique id can be generated by incrementing returned value from this fuction.
 */
export default function getGreatestId(arr) {
  return Math.max(...arr.map((e) => e.id), 0);
}
